/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vWx3u2t0b",
    "aws_user_pools_web_client_id": "2j725kgnbt3nk8ka4mef6vd6am",
    "oauth": {
        "domain": "nowl-protect-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "machine-auth/api.request",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "http://localhost",
        "redirectSignOut": "http://localhost",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://at7ef5e7yna5jeyrmtmt3jekxa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
